play_action: "install"
public_keys_dir: "public_keys"
hadoop_config_only: "no"
hadoop_spnego_kerberos_principal: "{{ 'HTTP/_HOST@' ~ kerberos_realm }}"
hadoop_spnego_kerberos_keytab: "{{ keytabs_path	~ '/HTTP.keytab' }}"
hadoop_kms_spnego_kerberos_principal: "{{ 'HTTP/' ~ inventory_hostname ~ '@' ~ kerberos_realm }}"
hadoop_kms_spnego_kerberos_keytab: "{{ keytabs_path	~ '/HTTP.keytab' }}"
hadoop_kms_kerberos_principal: "{{ 'kms/' ~ inventory_hostname ~ '@' ~ kerberos_realm }}"
hadoop_kms_kerberos_keytab: "{{ keytabs_path	~ '/kms.keytab' }}"
# hadoop_kms_keystore: "{{ 'jceks://' ~  ( with_ozone | bool | ternary('ofs@' ~ ozone_omservice, 'hdfs@' ~ hdfs_nameservice) ) ~ '/kms/keytab/kms.keystore' }}"
hadoop_kms_keystore: "{{ 'jceks://file@/${user.home}/kms.keystore' }}"
