Client {
 com.sun.security.auth.module.Krb5LoginModule required
 debug=true
 storeKey=true
 useTicketCache=false
 useKeyTab=true
 keyTab="/home/mbarinstein/ozone/hadoop/files/kerberos/keytabs/hadoop.keytab"
 principal="hadoop"
 doNotPrompt=true
;};
