Client {
       com.sun.security.auth.module.Krb5LoginModule required
       doNotPrompt=true
       useKeyTab=true
       keyTab="/etc/security/keytabs/hbase.keytab"
       storeKey=true
       useTicketCache=false
       principal="hbase/astra181-scylla-01.internal@DOMAIN.COM"
;};
