Client {
       com.sun.security.auth.module.Krb5LoginModule required
       doNotPrompt=true
       useKeyTab=true
       keyTab="/etc/security/keytabs/NN.keytab"
       storeKey=true
       useTicketCache=false
       principal="NN/astra181-scylla-01.internal@DOMAIN.COM";
};
