pgjdbc {
       com.sun.security.auth.module.Krb5LoginModule required
       doNotPrompt=true
       useKeyTab=true
       keyTab="/etc/security/keytabs/hive.keytab"
       storeKey=true
       useTicketCache=false
       principal="hive/astra181-scylla-01.internal@DOMAIN.COM"
;};

Client {
       com.sun.security.auth.module.Krb5LoginModule required
       doNotPrompt=true
       useKeyTab=true
       keyTab="/etc/security/keytabs/hive.keytab"
       storeKey=true
       useTicketCache=false
       principal="hive/astra181-scylla-01.internal@DOMAIN.COM"
;};

com.sun.security.jgss.krb5.initiate {
       com.sun.security.auth.module.Krb5LoginModule required
       doNotPrompt=true
       useKeyTab=true
       keyTab="/etc/security/keytabs/hive.keytab"
       storeKey=true
       useTicketCache=false
       principal="hive/astra181-scylla-01.internal@DOMAIN.COM"
;};
