ZKSignerSecretProviderClient {
       com.sun.security.auth.module.Krb5LoginModule required
       doNotPrompt=true
       useKeyTab=true
       storeKey=true
       useTicketCache=false
       keyTab="/etc/security/keytabs/kms.keytab"
       principal="kms/astra181-scylla-01.internal@DOMAIN.COM"
;};
