spark.master                                yarn
spark.submit.deployMode                     client
#spark.driver.memory                         512m
#spark.executor.memory                       512m
#spark.yarn.am.memory                        1G
spark.eventLog.enabled                      true
spark.eventLog.dir                          ofs://omservice1/vol1/bucket1/spark-logs
spark.history.provider                      org.apache.spark.deploy.history.FsHistoryProvider
spark.history.fs.logDirectory               ofs://omservice1/vol1/bucket1/spark-logs
spark.history.fs.update.interval            10s
spark.history.ui.port                       18080
#spark.driver.extraClassPath                /home/hadoop/hive/lib/postgresql-42.5.6.jar
#spark.executor.extraClassPath              /home/hadoop/hive/lib/postgresql-42.5.6.jar
spark.hadoop.fs.AbstractFileSystem.ofs.impl org.apache.hadoop.fs.ozone.RootedOzFs

spark.ssl.enabled                           true
spark.ssl.keyStore                          /etc/security/certs/keystore.jks
spark.ssl.keyStorePassword                  passw0rd
spark.ssl.trustStore                        /etc/security/certs/truststore.jks
spark.ssl.trustStorePassword                passw0rd

spark.history.kerberos.enabled 	            true
spark.history.kerberos.principal            spark/astra181-scylla-01.internal@DOMAIN.COM
spark.history.kerberos.keytab               /etc/security/keytabs/spark.keytab
spark.kerberos.access.hadoopFileSystems     ofs://omservice1
