spark.master                               yarn
spark.submit.deployMode                    client
#spark.driver.memory                        512m
#spark.executor.memory                      512m
#spark.yarn.am.memory                      1G
spark.eventLog.enabled                     true
spark.eventLog.dir                         ofs://omservice1/vol1/bucket1/spark-logs
spark.history.provider                     org.apache.spark.deploy.history.FsHistoryProvider
spark.history.fs.logDirectory              ofs://omservice1/vol1/bucket1/spark-logs
spark.history.fs.update.interval           10s
spark.history.ui.port                      18080
#spark.driver.extraClassPath                /home/hadoop/hive/lib/postgresql-42.5.6.jar
#spark.executor.extraClassPath              /home/hadoop/hive/lib/postgresql-42.5.6.jar
# to enable exector metrics
spark.ui.prometheus.enabled                true
spark.executor.processTreeMetrics.enabled  true
spark.hadoop.fs.AbstractFileSystem.ofs.impl org.apache.hadoop.fs.ozone.RootedOzFs
